# Generated by Django 4.2 on 2023-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_order_shippingaddress_review_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
