# Generated by Django 4.2 on 2023-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_guest_alter_order_user_order_guest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='OrderPersonalDetails',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='guest',
            new_name='orderPersonalDetails',
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
