products = [
    {
        '_id': '1',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'imageSrc': 'https://storage.googleapis.com/download/storage/v1/b/natura_horti_static/o/images%2Fairpods.jpg?generation=1683971471981039&alt=media',
        'description':
            'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.51,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'iPhone 12 Pro 256GB Memory',
        'imageSrc': 'https://storage.googleapis.com/download/storage/v1/b/natura_horti_static/o/images%2Fairpods.jpg?generation=1683971471981039&alt=media',
        'description':
            'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 200.99,
        'countInStock': 0,
        'rating': 4.23,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Cannon EOS 80D DSLR Camera',
        'imageSrc': 'https://storage.googleapis.com/download/storage/v1/b/natura_horti_static/o/images%2Fairpods.jpg?generation=1683971471981039&alt=media',
        'description':
            'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
        'brand': 'Cannon',
        'category': 'Electronics',
        'price': 929.99,
        'countInStock': 5,
        'rating': 3.76,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Sony Playstation 4 Pro White Version',
        'imageSrc': 'https://storage.googleapis.com/download/storage/v1/b/natura_horti_static/o/images%2Fairpods.jpg?generation=1683971471981039&alt=media',
        'description':
            'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
        'brand': 'Sony',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5.00,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Logitech G-Series Gaming Mouse',
        'imageSrc': 'https://storage.googleapis.com/download/storage/v1/b/natura_horti_static/o/images%2Fairpods.jpg?generation=1683971471981039&alt=media',
        'description':
            'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
        'brand': 'Logitech',
        'category': 'Electronics',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.25,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Amazon Echo Dot 3rd Generation',
        'imageSrc': 'https://storage.googleapis.com/download/storage/v1/b/natura_horti_static/o/images%2Fairpods.jpg?generation=1683971471981039&alt=media',
        'description':
            'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
        'brand': 'Amazon',
        'category': 'Electronics',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4.93,
        'numReviews': 12,
    },
]
